# Generated by Django 5.1.6 on 2025-07-31 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_author_captions_post_author_name_post_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='post.post')),
            ],
        ),
    ]
