# Generated by Django 5.1.6 on 2025-08-01 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_comments_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='comments_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comments'),
        ),
    ]
