# Generated by Django 5.1.6 on 2025-08-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_comments_title_post_comments_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_number',
            field=models.IntegerField(null=True),
        ),
    ]
