# Generated by Django 5.1.6 on 2025-08-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comments_post_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_number',
        ),
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
